################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SX_SRCS := 
S_UPPER_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src \
src/boost/libs/asio/example/cpp03/allocation \
src/boost/libs/asio/example/cpp03/buffers \
src/boost/libs/asio/example/cpp03/chat \
src/boost/libs/asio/example/cpp03/echo \
src/boost/libs/asio/example/cpp03/fork \
src/boost/libs/asio/example/cpp03/http/client \
src/boost/libs/asio/example/cpp03/http/server \
src/boost/libs/asio/example/cpp03/http/server2 \
src/boost/libs/asio/example/cpp03/http/server3 \
src/boost/libs/asio/example/cpp03/http/server4 \
src/boost/libs/asio/example/cpp03/icmp \
src/boost/libs/asio/example/cpp03/invocation \
src/boost/libs/asio/example/cpp03/iostreams \
src/boost/libs/asio/example/cpp03/local \
src/boost/libs/asio/example/cpp03/multicast \
src/boost/libs/asio/example/cpp03/nonblocking \
src/boost/libs/asio/example/cpp03/porthopper \
src/boost/libs/asio/example/cpp03/serialization \
src/boost/libs/asio/example/cpp03/services \
src/boost/libs/asio/example/cpp03/socks4 \
src/boost/libs/asio/example/cpp03/spawn \
src/boost/libs/asio/example/cpp03/ssl \
src/boost/libs/asio/example/cpp03/timeouts \
src/boost/libs/asio/example/cpp03/timers \
src/boost/libs/asio/example/cpp03/tutorial/daytime1 \
src/boost/libs/asio/example/cpp03/tutorial/daytime2 \
src/boost/libs/asio/example/cpp03/tutorial/daytime3 \
src/boost/libs/asio/example/cpp03/tutorial/daytime4 \
src/boost/libs/asio/example/cpp03/tutorial/daytime5 \
src/boost/libs/asio/example/cpp03/tutorial/daytime6 \
src/boost/libs/asio/example/cpp03/tutorial/daytime7 \
src/boost/libs/asio/example/cpp03/tutorial/timer1 \
src/boost/libs/asio/example/cpp03/tutorial/timer2 \
src/boost/libs/asio/example/cpp03/tutorial/timer3 \
src/boost/libs/asio/example/cpp03/tutorial/timer4 \
src/boost/libs/asio/example/cpp03/tutorial/timer5 \
src/boost/libs/asio/example/cpp03/windows \
src/boost/libs/asio/example/cpp11/allocation \
src/boost/libs/asio/example/cpp11/buffers \
src/boost/libs/asio/example/cpp11/chat \
src/boost/libs/asio/example/cpp11/deferred \
src/boost/libs/asio/example/cpp11/echo \
src/boost/libs/asio/example/cpp11/executors \
src/boost/libs/asio/example/cpp11/files \
src/boost/libs/asio/example/cpp11/fork \
src/boost/libs/asio/example/cpp11/futures \
src/boost/libs/asio/example/cpp11/handler_tracking \
src/boost/libs/asio/example/cpp11/http/server \
src/boost/libs/asio/example/cpp11/invocation \
src/boost/libs/asio/example/cpp11/iostreams \
src/boost/libs/asio/example/cpp11/local \
src/boost/libs/asio/example/cpp11/multicast \
src/boost/libs/asio/example/cpp11/nonblocking \
src/boost/libs/asio/example/cpp11/operations \
src/boost/libs/asio/example/cpp11/parallel_group \
src/boost/libs/asio/example/cpp11/socks4 \
src/boost/libs/asio/example/cpp11/spawn \
src/boost/libs/asio/example/cpp11/ssl \
src/boost/libs/asio/example/cpp11/timeouts \
src/boost/libs/asio/example/cpp11/timers \
src/boost/libs/asio/example/cpp11/type_erasure \
src/boost/libs/asio/example/cpp14/deferred \
src/boost/libs/asio/example/cpp14/echo \
src/boost/libs/asio/example/cpp14/executors \
src/boost/libs/asio/example/cpp14/iostreams \
src/boost/libs/asio/example/cpp14/operations \
src/boost/libs/asio/example/cpp14/parallel_group \
src/boost/libs/asio/example/cpp17/coroutines_ts \
src/boost/libs/asio/example/cpp20/channels \
src/boost/libs/asio/example/cpp20/coroutines \
src/boost/libs/asio/example/cpp20/invocation \
src/boost/libs/asio/example/cpp20/operations \
src/boost/libs/asio/example/cpp20/type_erasure \
src/boost/libs/asio/test \
src/boost/libs/asio/test/execution \
src/boost/libs/asio/test/experimental \
src/boost/libs/asio/test/experimental/coro \
src/boost/libs/asio/test/generic \
src/boost/libs/asio/test/ip \
src/boost/libs/asio/test/latency \
src/boost/libs/asio/test/local \
src/boost/libs/asio/test/posix \
src/boost/libs/asio/test/properties/cpp03 \
src/boost/libs/asio/test/properties/cpp11 \
src/boost/libs/asio/test/properties/cpp14 \
src/boost/libs/asio/test/ssl \
src/boost/libs/asio/test/ts \
src/boost/libs/asio/test/windows \
src/boost/libs/thread/build \
src/boost/libs/thread/example \
src/boost/libs/thread/src \
src/boost/libs/thread/src/pthread \
src/boost/libs/thread/src/win32 \
src/boost/libs/thread/test/experimental/parallel/v1 \
src/boost/libs/thread/test/experimental/parallel/v2 \
src/boost/libs/thread/test/functional/invoke \
src/boost/libs/thread/test/functional/invoker \
src/boost/libs/thread/test \
src/boost/libs/thread/test/sync/conditions/condition_variable \
src/boost/libs/thread/test/sync/conditions/condition_variable_any \
src/boost/libs/thread/test/sync/conditions/cv_status \
src/boost/libs/thread/test/sync/conditions \
src/boost/libs/thread/test/sync/futures/async \
src/boost/libs/thread/test/sync/futures/future \
src/boost/libs/thread/test/sync/futures \
src/boost/libs/thread/test/sync/futures/packaged_task \
src/boost/libs/thread/test/sync/futures/promise \
src/boost/libs/thread/test/sync/futures/shared_future \
src/boost/libs/thread/test/sync/futures/when_all \
src/boost/libs/thread/test/sync/futures/when_any \
src/boost/libs/thread/test/sync/mutual_exclusion/deque_views \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/lock_guard \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/nested_strict_lock \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/reverse_lock \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/shared_lock/cons \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/shared_lock/locking \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/shared_lock/mod \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/shared_lock/obs \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/shared_lock \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/shared_lock_guard \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/strict_lock \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/unique_lock/cons \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/unique_lock/locking \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/unique_lock/mod \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/unique_lock/obs \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/unique_lock \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/upgrade_lock/cons \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/upgrade_lock/locking \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/upgrade_lock/mod \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/upgrade_lock/obs \
src/boost/libs/thread/test/sync/mutual_exclusion/locks/upgrade_lock \
src/boost/libs/thread/test/sync/mutual_exclusion/mutex \
src/boost/libs/thread/test/sync/mutual_exclusion/null_mutex \
src/boost/libs/thread/test/sync/mutual_exclusion/once/call_once \
src/boost/libs/thread/test/sync/mutual_exclusion/queue_views \
src/boost/libs/thread/test/sync/mutual_exclusion/recursive_mutex \
src/boost/libs/thread/test/sync/mutual_exclusion/recursive_timed_mutex \
src/boost/libs/thread/test/sync/mutual_exclusion/shared_mutex \
src/boost/libs/thread/test/sync/mutual_exclusion/sync_bounded_queue \
src/boost/libs/thread/test/sync/mutual_exclusion/sync_deque \
src/boost/libs/thread/test/sync/mutual_exclusion/sync_pq \
src/boost/libs/thread/test/sync/mutual_exclusion/sync_queue \
src/boost/libs/thread/test/sync/mutual_exclusion/synchronized_value \
src/boost/libs/thread/test/sync/mutual_exclusion/timed_mutex \
src/boost/libs/thread/test/sync/mutual_exclusion/with_lock_guard \
src/boost/libs/thread/test/threads/container \
src/boost/libs/thread/test/threads/this_thread/get_id \
src/boost/libs/thread/test/threads/this_thread/sleep_for \
src/boost/libs/thread/test/threads/this_thread/sleep_until \
src/boost/libs/thread/test/threads/thread/assign \
src/boost/libs/thread/test/threads/thread/constr \
src/boost/libs/thread/test/threads/thread/destr \
src/boost/libs/thread/test/threads/thread/id \
src/boost/libs/thread/test/threads/thread/members \
src/boost/libs/thread/test/threads/thread/non_members \
src/boost/libs/thread/test/threads/thread/static \
src/boost/libs/thread/tutorial \

